server:
  port: 9002
spring:
  application:
    name: nacos-payment-provider
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848 # 配置Nacos地址
        #server-addr: 192.168.242.132:1111 # 通过 linux 系统的 nginx 转发给 nacos 集群

management:
  endpoints:
    web:
      exposure:
        include: '*'